CREATE EXTENSION pgcrypto;
CREATE TABLE "user"
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lastname     VARCHAR(255)                            NOT NULL,
    firstname    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL UNIQUE,
    password     VARCHAR(255)                            NOT NULL,
    birthdate    Date,
    phone_number VARCHAR(255),
    role         VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

INSERT INTO "user" (lastname, firstname, email, password, birthdate, phone_number, role)
VALUES ('Azoud', 'Mustafa', 'azoud@test.com', crypt('mustafa', gen_salt('bf')), '07/02/1986', '0489354412',
        'ROLE_ADMIN'),
       ('Gauthier', 'Cateau', 'cateau@test.com', crypt('gauthier', gen_salt('bf')), '01/08/1984', null, 'ROLE_USER'),
       ('Draa', 'Samiha', 'draa@test.com', crypt('samiha', gen_salt('bf')), '12/05/1981', null, 'ROLE_USER');