CREATE TABLE address
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    street   varchar(255) NOT NULL,
    city     varchar(50) NOT NULL,
    zip_code varchar(24) NOT NULL,
    country   varchar(50) NOT NULL
);
CREATE TABLE car
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    brand                 varchar(255) NOT NULL,
    model                 varchar(50) NOT NULL,
    number_available_seat INT NOT NULL
);


CREATE TABLE route
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    departure_address_id INT NOT NULL,
    arrival_address_id   INT NOT NULL,
    departure_date       DATE NOT NULL,
    passenger_number     INT NOT NULL,
    route_price          DOUBLE PRECISION NOT NULL,
    car_id               INT NOT NULL,
    FOREIGN KEY (departure_address_id) REFERENCES address (id),
    FOREIGN KEY (arrival_address_id) REFERENCES address (id),
    FOREIGN KEY (car_id) REFERENCES car (id)
);